version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  db:
    image: postgres:17.2
    container_name: order_db
    environment:
      - POSTGRES_USER=hetot
      - POSTGRES_PASSWORD=0506
      - POSTGRES_DB=order_db
    ports:
      - '5432:5432'
    volumes:
      - .postgres_db:/var/lib/postgresql/data

  acceptor:
    build:
      context: ./order-acceptor
    ports:
      - "8080:8080"
    environment:
      KAFKA_URL: kafka:9092
      DATASOURCE_URL: jdbc:postgresql://db:5432/order_db
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - "./config/acceptor/application-docker.properties:/app/application-docker.properties"
    depends_on:
      - kafka
      - db

  processor:
    build:
      context: ./order-processor
    environment:
      KAFKA_URL: kafka:9092
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - "./config/processor/application-docker.properties:/app/application-docker.properties"
    depends_on:
      - kafka
      - db
      - acceptor
